backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Produkter"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beskrivning", name: "body", widget: "markdown" }
      - { label: "Pris", name: "price", widget: "number" }
      - { label: "Lagersaldo", name: "stock", widget: "number" }
      - { label: "Bild", name: "image", widget: "image" }
